stages:
  - clean
  - compile
  - build
  - copy
  - verify

mvn-clean:
  stage: clean
  script:
    - sudo mvn clean

mvn-compile:
  stage: compile
  script:
    - sudo mvn compile -DskipTests=true

java-build:
  image: maven:3.8-openjdk-17
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - sudo mvn package -DskipTests=true -Drevision=$CI_PIPELINE_IID
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "target/$CI_PROJECT_NAME*.jar"

move:
  stage: copy
  allow_failure: true
  script:
    - shopt -s nocaseglob
    - sudo cp $CI_PROJECT_DIR/target/GriefPrevention*.jar /opt/mc.indexoutofmj.net/plugins/plugins
    - shopt -u nocaseglob
